services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    # Для SQLite данные лучше сохранять в volume, чтобы они не пропадали
    # volumes:
    #   - ./backend:/app
    #   - db_data:/app/db_volume

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  db_data: