# Generated by Django 5.2.8 on 2025-11-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='name',
            field=models.CharField(default='New Game', max_length=255),
        ),
    ]
