# Generated by Django 5.2.8 on 2025-11-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameroom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
