# Generated by Django 5.2.8 on 2025-11-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_gameroom_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='room',
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('crew', 'Crewmate'), ('imposter', 'Imposter')], default=None, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RoomTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='game.gameroom')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_tasks', to='game.task')),
            ],
        ),
    ]
