# Generated by Django 5.2.8 on 2025-11-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_task_room_alter_player_role_roomtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='roomtask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='arduino_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
