# Generated by Django 5.2.8 on 2025-11-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_location_created_location_updated_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
