# Generated by Django 5.2.8 on 2025-11-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_location_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
