# Generated by Django 5.2.8 on 2025-11-18 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_location_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='location',
        ),
        migrations.AddField(
            model_name='roomtask',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_locations', to='game.location'),
        ),
    ]
