# Generated by Django 5.2.8 on 2025-11-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_task_location_roomtask_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
