# Generated by Django 5.2.8 on 2025-11-19 08:22

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_gameroom_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='map',
            field=models.ImageField(null=True, upload_to=game.models.content_file_name),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='progress',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
