# Generated by Django 5.2.8 on 2025-11-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_gameroom_map_gameroom_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='progress',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
