# Generated by Django 5.2.8 on 2025-11-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_gameroom_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtask',
            name='points',
            field=models.JSONField(null=True),
        ),
    ]
