# Generated by Django 5.2.8 on 2025-11-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_roomtask_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
