# Generated by Django 5.2.8 on 2025-12-01 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_gameroom_start_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomTask',
            new_name='GameTask',
        ),
        migrations.AlterField(
            model_name='taskplayer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_task_players', to='game.task'),
        ),
    ]
