# Generated by Django 5.2.8 on 2025-12-01 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_rename_roomtask_gametask_alter_taskplayer_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskPlayer',
            new_name='GameTaskPlayer',
        ),
        migrations.AlterField(
            model_name='gametaskplayer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_task_players', to='game.gametask'),
        ),
    ]
