# Generated by Django 5.2.8 on 2026-01-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_rename_taskplayer_gametaskplayer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('crew', 'Член экипажа'), ('imposter', 'Самозванец')], default=None, max_length=20, null=True),
        ),
    ]
