# Generated by Django 5.2.8 on 2026-01-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='auto_assign_role',
            field=models.BooleanField(default=True),
        ),
    ]
