# Generated by Django 5.2.8 on 2026-01-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_gameroom_auto_assign_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameroom',
            old_name='map',
            new_name='game_map',
        ),
    ]
