# Generated by Django 5.2.8 on 2026-02-09 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_rename_map_gameroom_game_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametask',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='game.player'),
        ),
    ]
