# Generated by Django 5.2.8 on 2026-02-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_gametask_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='GameTaskPlayer',
        ),
    ]
