# Generated by Django 5.2.8 on 2026-02-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_gametask_completed_at_delete_gametaskplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Перезарядка до'),
        ),
    ]
