# Generated by Django 5.2.8 on 2026-02-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_player_cooldown_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='emergency_meetings_blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='last_sabotage_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='meeting_cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='sabotage_cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='tasks_blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_ghost',
            field=models.BooleanField(default=False, verbose_name='Призрак'),
        ),
        migrations.AddField(
            model_name='player',
            name='kill_cooldown_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Перезарядка убийства до'),
        ),
    ]
