# Generated by Django 5.2.8 on 2026-02-12 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_gameroom_emergency_meetings_blocked_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('emergency', 'Экстренное собрание'), ('body_report', 'Обнаружение тела')], default='emergency', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(help_text='Длительность собрания в секундах')),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('called_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_called', to='game.player')),
                ('reported_player', models.ForeignKey(blank=True, help_text='Игрок, чье тело было обнаружено (только для body_report)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_deaths', to='game.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='game.gameroom')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='game.meeting')),
                ('voted_for', models.ForeignKey(blank=True, help_text='Игрок, за которого проголосовали. Null = пропустить голосование', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='game.player')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='game.player')),
            ],
            options={
                'unique_together': {('meeting', 'voter')},
            },
        ),
    ]
