# Generated by Django 5.2.8 on 2026-02-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_meeting_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_started',
            field=models.BooleanField(default=False, help_text='Started by admin trigger'),
        ),
    ]
