# Generated by Django 5.2.8 on 2026-02-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_meeting_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_location_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_location_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
