# Generated by Django 5.2.8 on 2026-02-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_player_last_location_x_player_last_location_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_ghost',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_location_x',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_location_y',
        ),
    ]
