# Generated by Django 5.2.8 on 2026-02-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_remove_player_is_ghost_remove_player_last_location_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
