# Generated by Django 5.2.8 on 2026-02-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_gameroom_is_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='winner',
            field=models.CharField(choices=[('crew', 'Член экипажа'), ('imposter', 'Самозванец')], default=None, max_length=20, null=True),
        ),
    ]
