# Generated by Django 5.2.8 on 2026-02-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_gameroom_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='reason',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
