# Generated by Django 5.2.8 on 2026-02-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_gameroom_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gametask',
            options={'ordering': ['location__name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-is_active']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['is_alive']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
    ]
